#!/bin/bash
    id=$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')
    name=$(xprop -id $id | awk '/_NET_WM_NAME/{$1=$2="";print}' | cut -d'"' -f2)
    echo $name |tr -d '\n' |python -c 'import json,sys; print("|" + json.dumps(sys.stdin.read()).strip("\"")[:35] + "|")' || exit 1
    #echo "| $name |" |cut -c 1-50|| exit 1
