#!/bin/bash
volume() {
#  amixer -D $MIXER get $SCONTROL $(capability)
    # pactl list sinks |grep -P "\tVolume" |grep -io [0-9]*% |head -1
    if [ `pactl list sinks |grep -P "\tMute"  |awk '{print $2}'` = "yes" ]; then
        echo ""
    else 
        echo "`pactl list sinks |grep -P "\tVolume" |grep -io [0-9]*% |head -1`"
    fi

}

format() {
  perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
  perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
  # If dB was selected, print that instead
  perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
  perl_filter+='"; exit}'
  perl -ne "$perl_filter"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  1) pavucontrol ;;
  3) pactl set-sink-mute 0 toggle ;;  # right click, mute/unmute
  4) pactl set-sink-volume 0 +10% ;; # scroll up, increase
  5) pactl set-sink-volume 0 -10% ;; # scroll down, decrease
esac

volume 
